---
- hosts: localhost
  vars_files:
    - group_vars/all/pass.yml
  connection: local
  gather_facts: yes

  tasks:
    - name: Create EC2 Instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "ansible-key"
        instance_type: "t2.micro"
        security_groups: ["default"]
        region: "eu-west-2" 
        aws_access_key: "{{ ec2_access_key }}" 
        aws_secret_key: "{{ ec2_secret_key }}"     
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
      loop:
        - { image: "ami-0e56583ebfdfc098f", name: "managed-node1" }
        - { image: "ami-0a94c8e4ca2674d5a", name: "managed-node2" }
        - { image: "ami-0a94c8e4ca2674d5a", name: "managed-node3" }
